### PR TITLE
Add roundtrip fuzzer

### PR DESCRIPTION
**Pull request by killercup**
Saw [your tweet](https://twitter.com/GEndignoux/status/930760532973547520) and had to play with this a bit! Another interesting fuzzer might be to run another lzma impl and compare the outputs from compress/decompress.

### CODE REVIEW

**Comment by gendx** [comment]
Looks awesome, thanks! For now the encoder is very simple so the round-trip may not hit all code paths. It could be nice to fuzz the decoder itself, e.g. starting with a file that decodes as "hello world" https://github.com/gendx/lzma-rs/blob/master/tests/lzma.rs#L100

To compare with other implementations, I guess the popular binding to liblzma from @alexcrichton https://crates.io/crates/lzma-sys is a good target, although I may need to implement .xz first.

**Comment by killercup** [comment]
The roundtrip fuzzer catches exactly 1000 code paths. Adding a decode-only fuzzer is quite simple (just removing lines, basically, and adding it to the Cargo.toml):

```rust
#![no_main]
#[macro_use] extern crate libfuzzer_sys;
extern crate lzma;

fuzz_target!(|data: &[u8]| {
    let mut decomp: Vec<u8> = Vec::with_capacity(data.len());
    let _ = lzma::decompress(&mut std::io::BufReader::new(data), &mut decomp);
});
```

Running this with `cargo fuzz run --release decode -- -rss_limit_mb=8072000000 -max_len=99999` (I got OOM errors without the first flag, and wanted to generate big inputs) quickly gets up to a coverage of around 950 code paths. The fuzzer-magic is able to determine which inputs trigger new code paths and generate more of these interesting inputs. After running this for a while, the `fuzz/corpus/decode/` directory should contain a few valid LZMA files.

But let's help the fuzzer a bit: `cp tests/files/*.lzma fuzz/corpus/decode/`. After this, it starts with 1007 code paths. Running it  for a few minutes makes it go up to 1011 (with diminishing returns).

**Comment by gendx** [comment]
That's great thanks! The OOM errors may be due to #7, I guess it depends on the OS.

For the decoding corpus, maybe smaller files would be more useful. The current test file is 54KB of compressed LMZA, but I have smaller tests inlined directly in the test source code.

I started working on LZMA2 decoding, but I will definitely add more fuzz targets after that!

**Comment by killercup** [comment]
> The OOM errors may be due to #7, I guess it depends on the OS.

It only occurs int he fuzzer context and works when run as a regular test. Probably something with how libfuzzer does things.

> For the decoding corpus, maybe smaller files would be more useful.

Probably, yeah. It'll increase the execs/sec and will yield results faster.

> I started working on LZMA2 decoding

Awesome! 🎉

**Pull request merged**
